name: Draft Release
on: push

permissions:
  pull-requests: write
  contents: write


jobs:
  draft-release:
    name: Draft Release PR
    needs:
      - lint-test
      - wporg-code-analysis
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create or Update Release PR
      run: |
        bash .bin/release-pr.sh